// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAx466CH5ytz_IJqhkXGxMa5zZLSao8UXw',
    appId: '1:532209339131:web:50b6d19918903a9b043e5e',
    messagingSenderId: '532209339131',
    projectId: 'gpt-jr-e7773',
    authDomain: 'gpt-jr-e7773.firebaseapp.com',
    storageBucket: 'gpt-jr-e7773.firebasestorage.app',
    measurementId: 'G-642R22WRG9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCE5AAwV-rRaJf4a2zWRD-uEvh1vVryEmU',
    appId: '1:532209339131:android:c7cc0403e29b279a043e5e',
    messagingSenderId: '532209339131',
    projectId: 'gpt-jr-e7773',
    storageBucket: 'gpt-jr-e7773.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2Gsu8m-M5n8tGaD8wx6Ula-KYurTnkoU',
    appId: '1:532209339131:ios:dd03531be0e61f64043e5e',
    messagingSenderId: '532209339131',
    projectId: 'gpt-jr-e7773',
    storageBucket: 'gpt-jr-e7773.firebasestorage.app',
    iosBundleId: 'com.example.gptJr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2Gsu8m-M5n8tGaD8wx6Ula-KYurTnkoU',
    appId: '1:532209339131:ios:dd03531be0e61f64043e5e',
    messagingSenderId: '532209339131',
    projectId: 'gpt-jr-e7773',
    storageBucket: 'gpt-jr-e7773.firebasestorage.app',
    iosBundleId: 'com.example.gptJr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAx466CH5ytz_IJqhkXGxMa5zZLSao8UXw',
    appId: '1:532209339131:web:fb946ce78f88e172043e5e',
    messagingSenderId: '532209339131',
    projectId: 'gpt-jr-e7773',
    authDomain: 'gpt-jr-e7773.firebaseapp.com',
    storageBucket: 'gpt-jr-e7773.firebasestorage.app',
    measurementId: 'G-KSTXR1HD47',
  );
}
