default_platform(:android)

platform :android do
  desc "Build and distribute release APK to Firebase App Distribution"
  lane :firebase do
    sh "flutter build apk --release"

    firebase_app_distribution(
      firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
      app: ENV["FASTLANE_FIREBASE_APP_ID"],
      apk_path: "../build/app/outputs/flutter-apk/app-release.apk", # ← ✅ FIXED
      groups: "testers",
      release_notes: "Automated build from GitHub Actions 🚀"
    )
  end
end
