name: Build and Distribute APK

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build Release APK and Upload to Firebase
    runs-on: ubuntu-latest

    env:
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
      FASTLANE_FIREBASE_APP_ID: ${{ secrets.FASTLANE_FIREBASE_APP_ID }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.29.2"
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/key.jks

      - name: Install Ruby and Bundler
        run: |
          sudo apt-get update
          sudo apt-get install -y ruby-full
          gem install bundler --user-install
          echo 'export PATH="$HOME/.local/share/gem/ruby/$(ruby -e "puts RUBY_VERSION")/bin:$PATH"' >> $GITHUB_ENV

      - name: Build and distribute using Fastlane
        run: |
          export PATH="$HOME/.local/share/gem/ruby/$(ruby -e 'print RUBY_VERSION')/bin:$PATH"
          cd android
          bundle config set --local path vendor/bundle
          bundle install
          bundle exec fastlane firebase
